from dataclasses import dataclass
from typing import Type


@dataclass(frozen=True)
class TokenType:
    name: str


TT: Type[TokenType] = TokenType

OPEN_PAREN = TT(name="OPEN_PAREN")
CLOSE_PAREN = TT("CLOSE_PAREN")
OPEN_BRACE = TT("OPEN_BRACE")
CLOSE_BRACE = TT("CLOSE_BRACE")
OPEN_BRACKET = TT("OPEN_BRACKET")
CLOSE_BRACKET = TT("CLOSE_BRACKET")
COMMA = TT("COMMA")
QUESTION = TT("QUESTION")
DOT = TT("DOT")
MINUS = TT("MINUS")
PLUS = TT("PLUS")

COLON = TT("COLON")
AT = TT("@")
SEMICOLON = TT("SEMICOLON")
SLASH = TT("SLASH")

STAR = TT("STAR")
BANG = TT("BANG")
BANG_EQUAL = TT("BANG_EQUAL")
EQUAL = TT("EQUAL")

EQUAL_EQUAL = TT("EQUAL_EQUAL")
GREATER = TT("GREATER")

GREATER_EQUAL = TT("GREATER_EQUAL")
LESS = TT("LESS")

LESS_EQUAL = TT("LESS_EQUAL")

IDENTIFIER = TT("IDENTIFIER")

STRING = TT("STRING")

NUMBER = TT("NUMBER")

AND = TT("AND")
BINAND = TT("BINAND")
CLASS = TT("CLASS")
ELSE = TT("ELSE")
FALSE = TT("FALSE")
FUN = TT("FUN")
FOR = TT("FOR")
IF = TT("IF")
NULL = TT("NULL")
OR = TT("OR")
BINOR = TT("BINOR")
XOR = TT("XOR")
PRINT = TT("PRINT")
RETURN = TT("RETURN")
SUPER = TT("SUPER")
THIS = TT("THIS")
TRUE = TT("TRUE")
VAR = TT("VAR")
WHILE = TT("WHILE")
WHITESPACE = TT("WHITESPACE")

LINE_COMMENT = TT("LINE_COMMENT")
MULTI_LINE_COMMENT = TT("MULTI_LINE_COMMENT")
